Relax numpy version requirements
As of recent updates to conda-build, it doesn't like version specifications
like `numpy >=1.8`. You get the following error:

  Error: python and numpy versions should only be major.minor, like 2.7. Got >=1.8.

This PR should resolve this difficulty and allow these packages to be built.